spring.application.name=KTB4_Finn_Week6


spring.datasource.url=jdbc:h2:mem:community
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true